- name: Config PAT
 hots: casr1000
 gather_facts: false

 tasks:
  - name: Configurer le NAT
    cisco.ios.ios_config:
       lines:
         - acces-list2 permit 192.168.{{item}}.0 0.0.0.255
       loop:
           - 2
           - 3
           - 4
  - name: pool NAT
    cisco.ios.ios_config:
       lines:
         -ip nat pool 192.168.103.221 prefix 23

  - name: Configurer le NAT
    cisco.ios.ios_config:
       lines: ip naat outside
       parents: int g1
  
  - name: poolNAT
    cisco.ios.ios_config:
       lines:ip nat inside
